import Footer from "@/app/layouts/footer";
import Navbar from "@/app/layouts/navbar";
import Cakerecommend from "./components/section-one";
import Cakemenu from "./components/section-two";


export const metadata = {
    title: "Bakery House` - Products Cake",
    description: "Generated by create next app",
  };


export default function Cakepage(){
    const pageId = 2;
    return (
        <>
            <Navbar pageId ={pageId}/>
            <main className="w-full min-h-screen bg-white">
                <Cakerecommend/>
                <Cakemenu/>
            </main>
            <Footer/>
        </>
    );
}