import Footer from "../layouts/footer";
import Navbar from "../layouts/navbar";
import BakeryMap from "./components/map";

export const metadata = {
    title: "Bakery House` - Contact us",
    description: "Generated by create next app",
  };


export default function Location(){
    const pageId = 4;
    return (
        <>
            <Navbar pageId={pageId}/>
            <main className="w-full min-h-screen bg-white">
                <div>
                    <BakeryMap/>
                </div>
            </main>
            <Footer/>
        </>
    );
}