import Footer from "@/app/layouts/footer";
import Navbar from "@/app/layouts/navbar";
import CoffeeTeaRecommend from "./components/section-one";
import CoffeeTeaMenu from "./components/section-two";

export const metadata = {
    title: "Bakery House` - Products Coffee & Tea",
    description: "Generated by create next app",
  };



export default function CoffeeTeapage(){
        const pageId = 2;
        return (
            <>
                <Navbar pageId={pageId}/>
                <main className="w-full min-h-screen bg-white">
                    <CoffeeTeaRecommend/>
                    <CoffeeTeaMenu/>
                </main>
                <Footer/>
            </>
        );
}