import Footer from "@/app/layouts/footer";
import Navbar from "@/app/layouts/navbar";
import Cookierecommend from "./components/section-one";
import Cookiemenu from "./components/section-two";

export const metadata = {
    title: "Bakery House` - Products Cookie",
    description: "Generated by create next app",
  };



export default function Cookiepage(){
    const pageId = 2;

    return (
        <>
            <Navbar pageId={pageId}/>
            <main className="w-full min-h-screen bg-white">
                <Cookierecommend/>
                <Cookiemenu/>
            </main>
            <Footer/>
        </>
    );
}