import Footer from "../layouts/footer";
import Navbar from "../layouts/navbar";
import Productsection from "./components/landing/section";

export const metadata = {
    title: "Bakery House` - Products",
    description: "Generated by create next app",
  };


export default function Product(){
    const pageId = 2;
    return (
        <>
            <Navbar pageId={pageId}/>
            <main className="w-full min-h-screen bg-white pt-20">
                <Productsection/>
            </main>
            <Footer/>
        </>
    );
}