import Footer from "../layouts/footer";
import Navbar from "../layouts/navbar";
import ReviewSection from "./components/review-landing";

export const metadata = {
    title: "Bakery House` - Reviews",
    description: "Generated by create next app",
  };



export default function ReviewPage(){
    const pageId = 3;
    return (
        <>
            <Navbar pageId={pageId}/>
            <main className="w-full min-h-screen bg-white">
                <ReviewSection/>
            </main>
            <Footer/>
        </>
    );
}