import Navbar from "@/app/layouts/navbar";
import Recommendbread from "./components/recommend";
import Breadproducts from "./components/breadmenu";
import Footer from "@/app/layouts/footer";
import Breadmenu from "./components/breadmenu";

export const metadata = {
    title: "Bakery House` - Products Bread",
    description: "Generated by create next app",
  };


export default function Breadhome(){
    const pageId = 2;
    return (
        <>
            <Navbar pageId={pageId}/>
            <main className="w-full min-h-screen bg-white">
                <Recommendbread/>
                <Breadmenu/>
            </main>
            <Footer/>
        </>
    );
}